config/routes.rb
JudoHp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'
  
  match '/registrierung', to: 'users#new'
  match '/anmelden', to: 'sessions#new'
  match '/abmelden', to: 'sessions#destroy', via: :delete
  
  match '/kontakt', to: 'static_pages#contact'
  match '/hilfe', to: 'static_pages#help'
  match '/impressum', to: 'static_pages#impressum'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private
  
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  include SessionsHelper
end

app/controllers/sessions_controller.rb
# coding: utf-8

class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Ungültige E-Mail/Passwort Kombination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def impressum
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
# coding: utf-8

class UsersController < ApplicationController
  before_filter :signed_in_user,  only: [:index, :edit, :update]
  before_filter :correct_user,    only: [:edit, :update]
  before_filter :admin_user,      only: :destroy
  
  def show
    @user = User.find(params[:id])
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Willkommen auf der Judo-Homepage"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profil aktualisiert"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Benutzer gelöscht!"
    redirect_to users_path
  end

  private

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to anmelden_path, notice: "Bitte anmelden"
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
  
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Gibt den vollen Titel für einzelne Seiten zurück
  def full_title(page_title)
    base_title = "Judo-Homepage"
    if page_title.empty?
    base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
  
  def store_location
    session[:return_to] = request.fullpath
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small> Judo-Homepage by <a href="http://tonifreitag.de/">Toni Freitag</a> </small>
	<nav>
		<ul>
			<li>
				<%= link_to "Impressum", impressum_path %>
			</li>
			<li>
				<%= link_to "Hilfe",hilfe_path %>
			</li>
			<li>
				<%= link_to "Kontakt", kontakt_path %>
			</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<!--<div class="logo">-->
			<%= link_to "Judo-Homepage", root_path, id: "logo" %>
			<!--</div>-->
			<nav>
				<ul class="nav pull-right">
					<li>
						<%= link_to "Startseite", root_path %>
					</li>
					<% if signed_in? %>
					<li>
						<%= link_to "Benutzer", users_path %>
					</li>
					<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li>
								<%= link_to "Profil", current_user %>
							</li>
							<li>
								<%= link_to "Einstellungen", edit_user_path(current_user) %>
							</li>
							<li class="divider"></li>
							<li>
								<%= link_to "Abmelden", abmelden_path, method: "delete" %>
							</li>
						</ul>
					</li>
					<% else %>
					<li>
						<%= link_to "Anmelden", anmelden_path %>
					</li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>

		<%= render 'layouts/shim' %>

	</head>
	<body>

		<%= render 'layouts/header' %>

		<div class="container">
			
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			
			<%= yield %>
			
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
			
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error explanation">
		<div class="alert alert-error">
			Im Formular <%= t('plural.is', :count => @user.errors.count) %> <%= @user.errors.count %> Fehler.
		</div>
		
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Kontakt') %>
<h1>Kontakt</h1>
<p>
Auf dieser Seite soll ein Formular zur Verfügung gestellt werden, wodurch eine Nachricht an den Betreiber gesendet wird.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Hilfe') %>

<h1>Hilfe</h1>
<p>
	Auf dieser Seite werden Hilfestellungen zur Applikation angezeigt
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
<h1>Willkommen auf der Startseite der Judo-Homepage</h1>
<h2>
Das ist die Startseite!
</h2>
<%= link_to "Jetzt Registrieren!", registrierung_path, class: "btn btn-large btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/static_pages/impressum.html.erb
<% provide(:title, 'Impressum') %>

<h1>Impressum</h1>
<p>
	Dies ist das Impressum
</p>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 52 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
	| <%= link_to "löschen", user, method: :delete, confirm: "Sind sie sicher?" %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Benutzer bearbeiten") %>
<h1>Profil aktualisieren</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
			
			<%= f.label :name %>
			<%= f.text_field :name %>
			
			<%= f.label :email %>
			<%= f.text_field :email %>
			
			<%= f.label :password %>
			<%= f.password_field :password %>
			
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %>
			
			<%= f.submit "Änderungen speichern", class: "btn btn-large btn-primary" %>
		<% end %>
		
		<%= gravatar_for @user %>
		<a href="http://gravatar.com/emails">ändern</a>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Alle Benutzer') %>
<h1>Alle Benutzer</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Registrierung') %>
<h1>Registrierung</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
		
			<%= f.label :name %>
			<%= f.text_field :name %>
			
			<%= f.label :email %>
			<%= f.text_field :email %>
			
			<%= f.label :password %>
			<%= f.password_field :password %>
			
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %>
			
			<%= f.submit "Account erstellen", class: "btn btn-large btn-primary" %>
			
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>